//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string PicUrl { get; set; }
        public double Value { get; set; }
        public string Path { get; set; }
        public int CategoryId { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
